version: '2'
services:
  seed:
    image: "guntherw/akka-cluster-cheatsheet:1.0"
    hostname: "seednode"
    command: "-Dakka.remote.netty.tcp.hostname=seednode"

  node:
    image: "guntherw/akka-cluster-cheatsheet:1.0"
    links: ["seed:seednode"]